//ĐỊNH NGHĨA PERMISSION (RÕ – KHÔNG MƠ HỒ)
export const PERMISSIONS = {
  // USER
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_RESTORE: "USER_RESTORE",
  USER_VIEW_DETAIL: "USER_VIEW_DETAIL",
  USER_CHANGE_PASSWORD: "USER_CHANGE_PASSWORD",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",

  //ROLE
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_ASSIGN_PERMISSIONS: "ROLE_ASSIGN_PERMISSIONS",

  //PERMISSION
  PERMISSION_VIEW: "PERMISSION_VIEW",
  PERMISSION_CREATE: "PERMISSION_CREATE",
  PERMISSION_UPDATE: "PERMISSION_UPDATE",
  PERMISSION_DELETE: "PERMISSION_DELETE",

  // DOCUMENT
  DOCUMENT_VIEW: "DOCUMENT_VIEW",
  DOCUMENT_CREATE: "DOCUMENT_CREATE",
  DOCUMENT_VIEW_DETAIL: "DOCUMENT_VIEW_DETAIL",
  DOCUMENT_UPDATE: "DOCUMENT_UPDATE",
  DOCUMENT_DELETE: "DOCUMENT_DELETE",

  // DEPARTMENT
  DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
  DEPARTMENT_VIEW_DETAIL: "DEPARTMENT_VIEW_DETAIL",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_DELETE: "DEPARTMENT_DELETE",

  // AUDIT
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_VIEW_DETAIL: "AUDIT_VIEW_DETAIL",
  AUDIT_VIEW_DASHBOARD: "AUDIT_VIEW_DASHBOARD",

  // SYSTEM
  SYSTEM_SETTING: "SYSTEM_SETTING",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",

  // ASSET (Giai đoạn 1 — quản lý tài sản/thiết bị IT)
  ASSET_VIEW: "ASSET_VIEW",
  ASSET_VIEW_DETAIL: "ASSET_VIEW_DETAIL",
  ASSET_CREATE: "ASSET_CREATE",
  ASSET_UPDATE: "ASSET_UPDATE",
  ASSET_DELETE: "ASSET_DELETE",
  ASSET_DELETE_PERMANENT: "ASSET_DELETE_PERMANENT", // xoá vĩnh viễn — rủi ro cao, tách riêng khỏi ASSET_DELETE (soft delete)
  ASSET_ASSIGN: "ASSET_ASSIGN", // cấp phát / luân chuyển / thu hồi (Giai đoạn 2)
  ASSET_ALERTS_TRIGGER: "ASSET_ALERTS_TRIGGER", // chạy tay cảnh báo bảo hành/bảo trì (Giai đoạn 4, để test/chạy thủ công ngoài lịch cron)
  ASSET_EXCEL_EXPORT: "ASSET_EXCEL_EXPORT", // xuất Excel hàng loạt (Giai đoạn 5)
  ASSET_EXCEL_IMPORT: "ASSET_EXCEL_IMPORT", // nhập Excel hàng loạt (Giai đoạn 5)
  ASSET_INVENTORY_CHECK: "ASSET_INVENTORY_CHECK", // quét QR kiểm kê / check-in (Giai đoạn 5)
  ASSET_DISPOSE: "ASSET_DISPOSE", // dành cho Giai đoạn 3 (thanh lý qua workflow Document)

  // ASSET CATEGORY
  ASSET_CATEGORY_VIEW: "ASSET_CATEGORY_VIEW",
  ASSET_CATEGORY_CREATE: "ASSET_CATEGORY_CREATE",
  ASSET_CATEGORY_UPDATE: "ASSET_CATEGORY_UPDATE",
  ASSET_CATEGORY_DELETE: "ASSET_CATEGORY_DELETE",
  ASSET_CATEGORY_DELETE_PERMANENT: "ASSET_CATEGORY_DELETE_PERMANENT", // xoá vĩnh viễn — rủi ro cao, cùng nguyên tắc với ASSET_DELETE_PERMANENT

  /**
   * Medical Equipment — Permission constants
   *
   * QUAN TRỌNG — cách tích hợp vào codebase thật:
   * File này được thiết kế để MERGE vào constant `PERMISSIONS` hiện có của dự án
   * (03_CODEBASE_MAP.md nhắc tới "Constants: ... permissions ...", nhưng đường dẫn
   * file thật chưa được xác nhận trong project memory — cần bạn xác nhận path thật,
   * VD: `src/shared/constants/permission.constant.ts`).
   *
   * KHÔNG merge chung namespace với `ASSET_*` — lý do đã chốt ở
   * 18_MEDICAL_EQUIPMENT_DESIGN.md §6 (D-MED-003): tránh làm nặng thêm nợ kỹ thuật
   * permission naming drift (SEC-002/D-010) đang là backlog P0 cần dọn riêng.
   *
   * Cách merge đề xuất (KHÔNG tự động làm — cần review PR):
   * ```ts
   * // permission.constant.ts (file hiện có)
   * import { MEDICAL_EQUIPMENT_PERMISSIONS } from "./medicalEquipment.permission.constant";
   *
   * export const PERMISSIONS = {
   *   ...existingPermissionsObject,
   *   ...MEDICAL_EQUIPMENT_PERMISSIONS,
   * } as const;
   * ```
   *
   * Nguồn thiết kế: 18_MEDICAL_EQUIPMENT_DESIGN.md §6
   */
  // Equipment
  MEDICAL_EQUIPMENT_VIEW: "MEDICAL_EQUIPMENT_VIEW",
  MEDICAL_EQUIPMENT_VIEW_DETAIL: "MEDICAL_EQUIPMENT_VIEW_DETAIL",
  MEDICAL_EQUIPMENT_CREATE: "MEDICAL_EQUIPMENT_CREATE",
  MEDICAL_EQUIPMENT_UPDATE: "MEDICAL_EQUIPMENT_UPDATE",
  MEDICAL_EQUIPMENT_DELETE: "MEDICAL_EQUIPMENT_DELETE",
  MEDICAL_EQUIPMENT_DELETE_PERMANENT: "MEDICAL_EQUIPMENT_DELETE_PERMANENT",

  // Relocate (đổi department/location) — D-MED-007, action riêng, KHÔNG đi qua
  // MEDICAL_EQUIPMENT_UPDATE, nhất quán với nguyên tắc "generic update không đổi
  // department" áp dụng cho Asset (07_BUSINESS_RULES.md).
  MEDICAL_EQUIPMENT_RELOCATE: "MEDICAL_EQUIPMENT_RELOCATE",

  // Calibration / Inspection
  MEDICAL_EQUIPMENT_CALIBRATE: "MEDICAL_EQUIPMENT_CALIBRATE",
  MEDICAL_EQUIPMENT_QUARANTINE_OVERRIDE:
    "MEDICAL_EQUIPMENT_QUARANTINE_OVERRIDE",

  // Category
  MEDICAL_EQUIPMENT_CATEGORY_VIEW: "MEDICAL_EQUIPMENT_CATEGORY_VIEW",
  MEDICAL_EQUIPMENT_CATEGORY_CREATE: "MEDICAL_EQUIPMENT_CATEGORY_CREATE",
  MEDICAL_EQUIPMENT_CATEGORY_UPDATE: "MEDICAL_EQUIPMENT_CATEGORY_UPDATE",
  MEDICAL_EQUIPMENT_CATEGORY_DELETE: "MEDICAL_EQUIPMENT_CATEGORY_DELETE",

  // UPLOAD
  UPLOAD_FILES: "UPLOAD_FILES",
  VIEW_FILES: "VIEW_FILES",
  VIEW_FILE_DETAIL: "VIEW_FILE_DETAIL",
  DELETE_FILE: "DELETE_FILE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
