/**
 * Copy CHÍNH XÁC từ backend/src/shared/constants/permission.constant.ts
 * (2026-09-05) — KHÔNG tự đặt permission mới. FE_FOUNDATION_SPEC.md Mục 2, 9.
 * Khi backend đổi permission, đối chiếu lại file này — KHÔNG tự suy đoán.
 */
export const PERMISSIONS = {
  // USER
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_RESTORE: "USER_RESTORE",
  USER_VIEW_DETAIL: "USER_VIEW_DETAIL",
  USER_CHANGE_PASSWORD: "USER_CHANGE_PASSWORD",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  // Roadmap C1 (Xác thực 2 lớp qua email OTP, DEV-068, 2026-09-19)
  USER_RESET_2FA: "USER_RESET_2FA",
  // Roadmap C2 (Quản lý phiên đăng nhập, DEV-069, 2026-09-19)
  SESSION_VIEW_ALL: "SESSION_VIEW_ALL",
  SESSION_REVOKE_ALL: "SESSION_REVOKE_ALL",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",

  // ROLE
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_ASSIGN_PERMISSIONS: "ROLE_ASSIGN_PERMISSIONS",

  // PERMISSION
  PERMISSION_VIEW: "PERMISSION_VIEW",
  PERMISSION_CREATE: "PERMISSION_CREATE",
  PERMISSION_UPDATE: "PERMISSION_UPDATE",
  PERMISSION_DELETE: "PERMISSION_DELETE",

  // POLICY (ABAC — runtime CHƯA áp dụng, xem AUTH_RBAC_MAP.md Mục 2.4)
  POLICY_VIEW: "POLICY_VIEW",
  POLICY_CREATE: "POLICY_CREATE",
  POLICY_UPDATE: "POLICY_UPDATE",
  POLICY_DELETE: "POLICY_DELETE",

  // DOCUMENT
  DOCUMENT_VIEW: "DOCUMENT_VIEW",
  DOCUMENT_CREATE: "DOCUMENT_CREATE",
  DOCUMENT_VIEW_DETAIL: "DOCUMENT_VIEW_DETAIL",
  DOCUMENT_UPDATE: "DOCUMENT_UPDATE",
  DOCUMENT_DELETE: "DOCUMENT_DELETE",
  // MỚI (DEV-040, 2026-09-10) — cờ riêng bypass department-scoping cho hành
  // động XEM document (list/chi tiết/reports), không dùng để guard route/UI
  // nào ở FE (chỉ backend đọc), thêm vào đây để giữ đúng cam kết "Copy CHÍNH
  // XÁC từ backend" ở đầu file.
  DOCUMENT_VIEW_ALL_DEPARTMENTS: "DOCUMENT_VIEW_ALL_DEPARTMENTS",

  // DOCUMENT — EXCEL
  DOCUMENT_EXCEL_EXPORT: "DOCUMENT_EXCEL_EXPORT",
  DOCUMENT_EXCEL_TEMPLATE: "DOCUMENT_EXCEL_TEMPLATE",
  DOCUMENT_EXCEL_IMPORT: "DOCUMENT_EXCEL_IMPORT",
  EXCEL_DEPARTMENT_SYNC: "EXCEL_DEPARTMENT_SYNC",
  DOCUMENT_EXCEL_HISTORY: "DOCUMENT_EXCEL_HISTORY",

  // WORKFLOW
  WORKFLOW_TEMPLATE_CREATE: "WORKFLOW_TEMPLATE_CREATE",
  WORKFLOW_SUBMIT: "WORKFLOW_SUBMIT",
  WORKFLOW_APPROVE: "WORKFLOW_APPROVE",
  WORKFLOW_REJECT: "WORKFLOW_REJECT",
  WORKFLOW_VIEW: "WORKFLOW_VIEW",
  WORKFLOW_CANCEL: "WORKFLOW_CANCEL",
  WORKFLOW_COMPLETE: "WORKFLOW_COMPLETE",

  // DEPARTMENT
  DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
  DEPARTMENT_VIEW_DETAIL: "DEPARTMENT_VIEW_DETAIL",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_DELETE: "DEPARTMENT_DELETE",

  // AUDIT
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_VIEW_DETAIL: "AUDIT_VIEW_DETAIL",
  AUDIT_VIEW_DASHBOARD: "AUDIT_VIEW_DASHBOARD",

  // SYSTEM
  SYSTEM_SETTING: "SYSTEM_SETTING",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",

  // DASHBOARD
  DASHBOARD_READ: "DASHBOARD_READ",

  // ASSET
  ASSET_VIEW: "ASSET_VIEW",
  ASSET_VIEW_DETAIL: "ASSET_VIEW_DETAIL",
  ASSET_CREATE: "ASSET_CREATE",
  ASSET_UPDATE: "ASSET_UPDATE",
  ASSET_DELETE: "ASSET_DELETE",
  ASSET_DELETE_PERMANENT: "ASSET_DELETE_PERMANENT",
  ASSET_ASSIGN: "ASSET_ASSIGN",
  ASSET_ALERTS_TRIGGER: "ASSET_ALERTS_TRIGGER",
  ASSET_EXCEL_EXPORT: "ASSET_EXCEL_EXPORT",
  ASSET_EXCEL_IMPORT: "ASSET_EXCEL_IMPORT",
  ASSET_INVENTORY_CHECK: "ASSET_INVENTORY_CHECK",
  ASSET_DISPOSE: "ASSET_DISPOSE",
  // Roadmap B2 (Lịch bảo trì chủ động, 2026-09-15)
  ASSET_MAINTENANCE_PLAN_VIEW: "ASSET_MAINTENANCE_PLAN_VIEW",
  ASSET_MAINTENANCE_PLAN_CREATE: "ASSET_MAINTENANCE_PLAN_CREATE",
  ASSET_MAINTENANCE_PLAN_UPDATE: "ASSET_MAINTENANCE_PLAN_UPDATE",

  // ASSET CATEGORY
  ASSET_CATEGORY_VIEW: "ASSET_CATEGORY_VIEW",
  ASSET_CATEGORY_CREATE: "ASSET_CATEGORY_CREATE",
  ASSET_CATEGORY_UPDATE: "ASSET_CATEGORY_UPDATE",
  ASSET_CATEGORY_DELETE: "ASSET_CATEGORY_DELETE",
  ASSET_CATEGORY_DELETE_PERMANENT: "ASSET_CATEGORY_DELETE_PERMANENT",

  // MEDICAL DEVICE
  MEDICAL_DEVICE_CREATE: "MEDICAL_DEVICE_CREATE",
  MEDICAL_DEVICE_VIEW: "MEDICAL_DEVICE_VIEW",
  MEDICAL_DEVICE_UPDATE: "MEDICAL_DEVICE_UPDATE",
  MEDICAL_DEVICE_CALIBRATE: "MEDICAL_DEVICE_CALIBRATE",
  MEDICAL_DEVICE_ALERTS_TRIGGER: "MEDICAL_DEVICE_ALERTS_TRIGGER",

  // UPLOAD
  UPLOAD_FILES: "UPLOAD_FILES",
  VIEW_FILES: "VIEW_FILES",
  VIEW_FILE_DETAIL: "VIEW_FILE_DETAIL",
  DELETE_FILE: "DELETE_FILE",

  // PERFORMANCE
  PERFORMANCE_VIEW: "PERFORMANCE_VIEW",

  // NOTIFICATION — self-scoped list/read/delete KHÔNG cần permission (FE-12).
  // 2 permission dưới đây CHỈ dành cho UI quản trị Notification (FE-13,
  // 2026-09-10): gửi thông báo hệ thống + xem thông báo của người khác.
  NOTIFICATION_BROADCAST: "NOTIFICATION_BROADCAST",
  NOTIFICATION_VIEW_ALL: "NOTIFICATION_VIEW_ALL",

  // Roadmap B3 (Quản lý vật tư tiêu hao, 2026-09-15)
  CONSUMABLE_VIEW: "CONSUMABLE_VIEW",
  CONSUMABLE_CREATE: "CONSUMABLE_CREATE",
  CONSUMABLE_UPDATE: "CONSUMABLE_UPDATE",
  CONSUMABLE_TRANSACTION_CREATE: "CONSUMABLE_TRANSACTION_CREATE",
  CONSUMABLE_ALERTS_TRIGGER: "CONSUMABLE_ALERTS_TRIGGER",

  // Nhóm vật tư tiêu hao (2026-09-16)
  CONSUMABLE_CATEGORY_VIEW: "CONSUMABLE_CATEGORY_VIEW",
  CONSUMABLE_CATEGORY_CREATE: "CONSUMABLE_CATEGORY_CREATE",
  CONSUMABLE_CATEGORY_UPDATE: "CONSUMABLE_CATEGORY_UPDATE",
  CONSUMABLE_CATEGORY_DELETE: "CONSUMABLE_CATEGORY_DELETE",

  // Roadmap B8 (Dự trù/đề xuất mua vật tư tiêu hao hàng tháng, DEV-067, 2026-09-18)
  CONSUMABLE_REQUEST_VIEW: "CONSUMABLE_REQUEST_VIEW",
  CONSUMABLE_REQUEST_CREATE: "CONSUMABLE_REQUEST_CREATE",
  CONSUMABLE_REQUEST_UPDATE: "CONSUMABLE_REQUEST_UPDATE",
  CONSUMABLE_REQUEST_FULFILL: "CONSUMABLE_REQUEST_FULFILL",

  // Roadmap B4 (Quản lý nhà cung cấp & hợp đồng bảo trì, 2026-09-16)
  VENDOR_VIEW: "VENDOR_VIEW",
  VENDOR_CREATE: "VENDOR_CREATE",
  VENDOR_UPDATE: "VENDOR_UPDATE",
  CONTRACT_VIEW: "CONTRACT_VIEW",
  CONTRACT_CREATE: "CONTRACT_CREATE",
  CONTRACT_UPDATE: "CONTRACT_UPDATE",
  CONTRACT_ALERTS_TRIGGER: "CONTRACT_ALERTS_TRIGGER",
  // Khôi phục hợp đồng đã huỷ (2026-09-16, DEV-058) — permission RIÊNG, không gộp vào CONTRACT_UPDATE
  CONTRACT_RESTORE: "CONTRACT_RESTORE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
